name: build
on:
  schedule:
  - cron: "5 0 * * *"
  push:
    branches:
      - master
  pull_request:

jobs:
  sync:
    name: Sync content
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Format documents
        uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --write ./docs/**/*.md
          commit_message: 'notion-md-gen: update articles (auto)'

