name: build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build And Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Deploy
        uses: saltbo/uptoc@master
        with:
          driver: qiniu
          region: cn-north-1
          bucket: saltbo-booklets
          exclude: .git,.github
          dist: .
        env:
          UPTOC_UPLOADER_AK: ${{ secrets.UPTOC_UPLOADER_KEYID }}
          UPTOC_UPLOADER_SK: ${{ secrets.UPTOC_UPLOADER_KEYSECRET }}